function setHomeView() {
	$('#view_name').html("Home View");
	$('#frame').html("<div style='text-align: center;'><img src='./icons/logo.png' style='margin-top: 100px;' /></div><div id='homeView' style='text-align: justify; margin: 200px; margin-top: 50px; font-size: 20px;'>Scorpius is a voice-controlled; cloud, Arduino and Android-powered rover that uses Artificial Intelligence and Computer Vision to address some current problems in robotics, including, among other things, line-following, obstacle-avoidance, voice control, natural language processing, motion &amp; face detection and remote surveyllance. He also has an autonomous Twitter account for active social networking.</div>");
}
function setCamView() {
	$('#view_name').html("Cam View");
	$('#frame').html("<div id='camView'><canvas id='camViewCamera'>Your browser doesn't support canvas. LOL.</canvas><div id='camViewImageProcessing'><div style='margin-bottom: 30px;'><strong>Image Processing Toolbox</strong></div><div id='pixMain'><form name='imgProcessing'><div class='imgProcessingLabel'><label for='imgProcessingRed'>RED SHIFT</label></div><div class='imgProcessingcheckbox'><input type='checkbox' name='imgProcessingRed' id='imgProcessingRed'/></div><br /><div class='imgProcessingLabel'><label for='imgProcessingGreen'>GREEN SHIFT</label></div><div class='imgProcessingcheckbox'><input type='checkbox' name='imgProcessingGreen' id='imgProcessingGreen'/></div><br /><div class='imgProcessingLabel'><label for='imgProcessingBlue'>BLUE SHIFT</label></div><div class='imgProcessingcheckbox'><input type='checkbox' name='imgProcessingBlue' id='imgProcessingBlue'/></div><br /><div class='imgProcessingLabel'><label for='imgProcessingNegative'>NEGATIVE</label></div><div class='imgProcessingcheckbox'><input type='checkbox' name='imgProcessingNegative' id='imgProcessingNegative'/></div><br /><div class='imgProcessingLabel'><label for='imgProcessingGray'>GRAY SCALE</label></div><div class='imgProcessingcheckbox'><input type='checkbox' name='imgProcessingGray' id='imgProcessingGray'/></div><br /><div class='imgProcessingLabel'><label for='imgProcessingNoise'>ADD NOISE</label></div><div class='imgProcessingcheckbox'><input type='checkbox' name='imgProcessingNoise' id='imgProcessingNoise'/></div><br /><div class='imgProcessingLabel'><label for='imgProcessingEdge'>EDGE DETECT</label></div><div class='imgProcessingcheckbox'><input type='checkbox' name='imgProcessingEdge' id='imgProcessingEdge'/></div><br /><div class='imgProcessingLabel'><label for='imgProcessingCon'>ADD CONTRAST</label></div><div class='imgProcessingcheckbox'><input type='checkbox' name='imgProcessingCon' id='imgProcessingCon'/></div><br /></form></div></div></div>");
	$('#camView').css('margin-left',(window.innerWidth/2-505)+'px');
}
function setSensorView() {
	$('#view_name').html("Sensors View");
	$('#frame').html("<div id='sensorView'><div id='sensorViewTable'><div id='sensorViewKeyHeader'>Name</div><div id='sensorViewValueHeader'>Status</div><div id='' class='sensorViewKey'>Compass</div><div id='sensorViewCompass' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Latitude</div><div id='sensorViewLatitude' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Longitude</div><div id='sensorViewLongitude' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Acceleration - X</div><div id='sensorViewAccX' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Acceleration - Y</div><div id='sensorViewAccY' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Acceleration - Z</div><div id='sensorViewAccZ' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Proximity</div><div id='sensorViewProximity' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>IR Down</div><div id='sensorViewIRDown' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Sonar Front</div><div id='sensorViewSonarFront' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Sonar Left</div><div id='sensorViewSonarLeft' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Sonar Right</div><div id='sensorViewSonarRight' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Battery</div><div id='sensorViewBattery' class='sensorViewValue'>-</div><div id='' class='sensorViewKey'>Temperature</div><div id='sensorViewTemperature' class='sensorViewValue'>-</div></div><div id='sensorViewCanvasFrame'><div id='sensorViewCompassfeed'><div style='margin-bottom: 5px; text-align: center; padding-top: 20px;'><strong>VISUALIZATION</strong><br /><br />COMPASS</div><canvas id='sensorViewCompassCanvas' height='150' width='300'></canvas></div><div id='sensorViewAccelerometer'><div style='margin-bottom: 5px; text-align: center;'>ACCELEROMETER</div><canvas id='sensorViewAccelerometerCanvas' height='150' width='300'></canvas></div></div></div>");
	$('#sensorView').css('margin-left',(window.innerWidth/2-475)+'px');
}
function setMapView() {
	$('#view_name').html("Map View");
	$('#frame').html("<div id='mapView'><div style='text-align: center; margin-top: 50px; margin-bottom: 10px;'>Traversed Route Map</div><canvas id='mapViewCanvas'>No Canvas</canvas><div style='text-align: center; margin-top: 10px;'>Scale : 1 px = 10 cm</div></div>");
	$('#mapView').css('margin-left',(window.innerWidth/2-300)+'px');
}
function setNNOutputView() {
	$('#view_name').html("Neural Network Output View");
	$('#frame').html("<div id='navView'><div><div id='navViewSonarLeftHeader'>Sonar Left</div><div id='navViewSonarFrontHeader'>Sonar Front</div><div id='navViewSonarRightHeader'>Sonar Right</div><div id='navViewIRDownHeader'>IR Down</div><div id='navViewProximityHeader'>Proximity</div><div id='navViewDestinationHeader'>Destination</div><div id='navViewDecisionHeader'>Decision</div></div><div><div id='navViewSonarLeftHeaderRow1' class='navViewRowBox'></div><div id='navViewSonarFrontHeaderRow1' class='navViewRowBox'></div><div id='navViewSonarRightHeaderRow1' class='navViewRowBox'></div><div id='navViewIRDownHeaderRow1' class='navViewRowBox'></div><div id='navViewProximityHeaderRow1' class='navViewRowBox'></div><div id='navViewDestinationHeaderRow1' class='navViewRowBox'></div><div id='navViewDecisionHeaderRow1' class='navViewRowBox'></div></div></div>");
	$('#navView').css('margin-left',(window.innerWidth/2-560)+'px');
}
function setAnalyticsView() {
	$('#view_name').html("Analytics View");
	$('#frame').html("<div id='analyticsView'><div style='text-align: center; margin-top: 50px; margin-bottom: 10px;'>Mobility</div><canvas id='analyticsViewMobilityCanvas'>No Canvas</canvas><div style='text-align: center; margin-top: 50px; margin-bottom: 10px;'>Power</div><canvas id='analyticsViewPowerCanvas'>No Canvas</canvas><div style='text-align: center; margin-top: 50px; margin-bottom: 10px;'>Neural Network System</div><canvas id='analyticsViewAICanvas'>No Canvas</canvas><div style='text-align: center; margin-top: 50px; margin-bottom: 10px;'>Temperature</div><canvas id='analyticsViewTemperatureCanvas' style='margin-bottom: 30px;'>No Canvas</canvas></div>");
	$('#analyticsView').css('margin-left',(window.innerWidth/2-300)+'px');
}
